### ISSUE TITLE
RequestSchedulerInterface is not instantiable

### ISSUE THREAD

**Issue by vmitchell85** [roach-php/core#18] opened 2022-02-01 02:37 UTC
Giving this project a go and I get the following error when attempting to run my spider.

tried PHP 8 and 8.1

```
Illuminate\Contracts\Container\BindingResolutionException
Target [RoachPHP\Scheduling\RequestSchedulerInterface] is not instantiable while building [RoachPHP\Core\Engine].
```

**Comment by ksassnowski** [comment] 2022-02-01 08:21
Duplicate of https://github.com/roach-php/laravel/issues/5. There’s an issue in the Laravel package if the config has not been published that I still need to fix.

**Closed by ksassnowski** 2022-02-01 08:21 UTC
